name: New Tool Integration
description: Keptn should integrate with this tool. Let's make it happen...
title: "[Integration]: "
labels: ["integration"]
assignees:
  - agardnerit
body:
  - type: markdown
    attributes:
      value: |
        Keptn is designed to work with any tool. Use this form to request a new integration for a tool you use / love.
        
        Integration requests that are "assisted" (that is, the requester [you] are willing to assist in developing this integration) will have a higher priority.
  - type: checkboxes
    id: existing
    attributes:
      label: Existing Integrations Checked
      description: I have checked [here](https://keptn.sh/integrations) that an integration does not already exist
      options:
        - label: Yes
          required: true
  - type: dropdown
    id: assisted
    attributes:
      label: Assisted
      description: Are you willing to assist during development of this integration?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: other_info
    attributes:
      label: Any other info?
      description: Any other info that might assist in developing / prioritising this integration?
      render: shell
